sonar.projectKey=crud-react-nodejs-mysql
sonar.projectName=CRUD React Node MySQL
sonar.sources=api,web/src
sonar.exclusions=**/node_modules/**,**/build/**,**/__tests__/**,**/*.test.js,web/src/index.js
sonar.tests=api/__tests__,web/src
sonar.test.inclusions=**/__tests__/**,**/*.test.js
sonar.javascript.lcov.reportPaths=reports/api/coverage/lcov.info,reports/web/coverage/lcov.info
sonar.sourceEncoding=UTF-8
